apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: talana-frontend
  namespace: talana
spec:
  project: default
  source:
    repoURL: https://github.com/nosenadayo/challenge_talana_frontend.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: talana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
