apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: talana-postgresql
  namespace: talana
spec:
  project: default
  source:
    repoURL: https://github.com/nosenadayo/challenge_talana_infra.git
    targetRevision: HEAD
    path: infrastructure/postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: talana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
