apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:13
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: talana_production
            - name: POSTGRES_USER
              value: talana_user
            - name: POSTGRES_PASSWORD
              value: talana_password
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/talana
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-pvc
